[tools]
go = "latest"
terraform = "latest"
kubectl = "latest"
helm = "latest"
trivy = "latest"
node = "lts"
uv = "latest"
fzf = "latest"
github-cli = "latest"
dotnet = "latest"
1password = "latest"
goreleaser = "latest"

[settings]
experimental = true
