[tools]
go = "latest"
terraform = "latest"
kubectl = "latest"
helm = "latest"
trivy = "latest"
node = "lts"
uv = "latest"
fzf = "latest"
github-cli = "latest"
dotnet = "latest"
1password = "latest"
goreleaser = "latest"
cue = "latest"
ghq = "latest"
azure-kubelogin = "latest"
yq = "latest"
sqlc = "latest"
cosign = "latest"
golangci-lint = "latest"
kustomize = "latest"
ripgrep = "latest"
shellcheck = "latest"
cargo-make = "latest"

[settings]
experimental = true
